import os

def w(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print(f'Wrote {path} ({len(text)} bytes)')

TAB = '  '

# ============================================================
# src/engine.ts — Pure game engine
# ============================================================
engine_lines = []
engine_lines.append('/**')
engine_lines.append(' * Ancient Go - Pure Game Engine')
engine_lines.append(' * Types, board operations, move logic, scoring.')
engine_lines.append(' * Zero CLI or UI dependencies — importable by tests and bots.')
engine_lines.append(' */')
engine_lines.append('')
engine_lines.append('// 1. Constants & Types')
engine_lines.append('')
engine_lines.append('export const EMPTY = 0 as const')
engine_lines.append('export const BLACK = 1 as const')
engine_lines.append('export const WHITE = 2 as const')
engine_lines.append('')
engine_lines.append('export type Cell = typeof EMPTY | typeof BLACK | typeof WHITE')
engine_lines.append('export type Board = Cell[][]')
engine_lines.append('')
engine_lines.append('export interface GameState {')
engine_lines.append(TAB + 'size: number')
engine_lines.append(TAB + 'board: Board')
engine_lines.append(TAB + 'currentPlayer: typeof BLACK | typeof WHITE')
engine_lines.append(TAB + 'captures: { [BLACK]: number; [WHITE]: number }')
engine_lines.append(TAB + 'history: string[]')
engine_lines.append(TAB + 'consecutivePasses: number')
engine_lines.append(TAB + 'gameOver: boolean')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export interface MoveResult {')
engine_lines.append(TAB + 'valid: boolean')
engine_lines.append(TAB + 'reason?: string')
engine_lines.append(TAB + 'newBoard?: Board')
engine_lines.append(TAB + 'captured?: number')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('// 2. Board Utilities')
engine_lines.append('')
engine_lines.append('export function createBoard(size: number): Board {')
engine_lines.append(TAB + 'return Array.from({ length: size }, () => Array<Cell>(size).fill(EMPTY))')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function cloneBoard(board: Board): Board {')
engine_lines.append(TAB + 'return board.map(row => [...row])')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function boardKey(board: Board): string {')
engine_lines.append(TAB + 'return board.map(row => row.join("")).join("|")')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function getNeighbors(r: number, c: number, size: number): [number, number][] {')
engine_lines.append(TAB + 'const dirs: [number, number][] = [[-1, 0], [1, 0], [0, -1], [0, 1]]')
engine_lines.append(TAB + 'const result: [number, number][] = []')
engine_lines.append(TAB + 'for (const [dr, dc] of dirs) {')
engine_lines.append(TAB * 2 + 'const nr = r + dr, nc = c + dc')
engine_lines.append(TAB * 2 + 'if (nr >= 0 && nr < size && nc >= 0 && nc < size) result.push([nr, nc])')
engine_lines.append(TAB + '}')
engine_lines.append(TAB + 'return result')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function findGroup(board: Board, r: number, c: number): [number, number][] {')
engine_lines.append(TAB + 'const color = board[r][c]')
engine_lines.append(TAB + 'if (color === EMPTY) return []')
engine_lines.append(TAB + 'const size = board.length')
engine_lines.append(TAB + 'const visited = new Set<number>()')
engine_lines.append(TAB + 'const group: [number, number][] = []')
engine_lines.append(TAB + 'const stack: [number, number][] = [[r, c]]')
engine_lines.append(TAB + 'while (stack.length > 0) {')
engine_lines.append(TAB * 2 + 'const [cr, cc] = stack.pop()!')
engine_lines.append(TAB * 2 + 'const key = cr * size + cc')
engine_lines.append(TAB * 2 + 'if (visited.has(key)) continue')
engine_lines.append(TAB * 2 + 'visited.add(key)')
engine_lines.append(TAB * 2 + 'group.push([cr, cc])')
engine_lines.append(TAB * 2 + 'for (const [nr, nc] of getNeighbors(cr, cc, size)) {')
engine_lines.append(TAB * 3 + 'if (!visited.has(nr * size + nc) && board[nr][nc] === color) stack.push([nr, nc])')
engine_lines.append(TAB * 2 + '}')
engine_lines.append(TAB + '}')
engine_lines.append(TAB + 'return group')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function countLiberties(board: Board, group: [number, number][]): number {')
engine_lines.append(TAB + 'const size = board.length')
engine_lines.append(TAB + 'const liberties = new Set<number>()')
engine_lines.append(TAB + 'for (const [r, c] of group) {')
engine_lines.append(TAB * 2 + 'for (const [nr, nc] of getNeighbors(r, c, size)) {')
engine_lines.append(TAB * 3 + 'if (board[nr][nc] === EMPTY) liberties.add(nr * size + nc)')
engine_lines.append(TAB * 2 + '}')
engine_lines.append(TAB + '}')
engine_lines.append(TAB + 'return liberties.size')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('// 3. Star Points')
engine_lines.append('')
engine_lines.append('export function isStarPoint(r: number, c: number, size: number): boolean {')
engine_lines.append(TAB + 'if (size === 9) return ([2, 4, 6].includes(r) && [2, 4, 6].includes(c))')
engine_lines.append(TAB + 'if (size === 13) return ([3, 6, 9].includes(r) && [3, 6, 9].includes(c))')
engine_lines.append(TAB + 'if (size === 19) { const s = [3, 9, 15]; return s.includes(r) && s.includes(c) }')
engine_lines.append(TAB + 'return false')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('// 4. Move Logic')
engine_lines.append('')
engine_lines.append('function tryPlaceStone(board: Board, r: number, c: number, color: Cell): MoveResult {')
engine_lines.append(TAB + 'const size = board.length')
engine_lines.append(TAB + 'if (board[r][c] !== EMPTY) {')
engine_lines.append(TAB * 2 + 'return { valid: false, reason: "Intersection is not empty." }')
engine_lines.append(TAB + '}')
engine_lines.append(TAB + 'const newBoard = cloneBoard(board)')
engine_lines.append(TAB + 'newBoard[r][c] = color')
engine_lines.append(TAB + 'let totalCaptured = 0')
engine_lines.append(TAB + 'const opponent: Cell = color === BLACK ? WHITE : BLACK')
engine_lines.append(TAB + 'for (const [nr, nc] of getNeighbors(r, c, size)) {')
engine_lines.append(TAB * 2 + 'if (newBoard[nr][nc] === opponent) {')
engine_lines.append(TAB * 3 + 'const enemyGroup = findGroup(newBoard, nr, nc)')
engine_lines.append(TAB * 3 + 'if (countLiberties(newBoard, enemyGroup) === 0) {')
engine_lines.append(TAB * 4 + 'for (const [cr, cc] of enemyGroup) newBoard[cr][cc] = EMPTY')
engine_lines.append(TAB * 4 + 'totalCaptured += enemyGroup.length')
engine_lines.append(TAB * 3 + '}')
engine_lines.append(TAB * 2 + '}')
engine_lines.append(TAB + '}')
engine_lines.append(TAB + 'const ownGroup = findGroup(newBoard, r, c)')
engine_lines.append(TAB + 'if (countLiberties(newBoard, ownGroup) === 0) {')
engine_lines.append(TAB * 2 + 'return { valid: false, reason: "Suicide is not allowed." }')
engine_lines.append(TAB + '}')
engine_lines.append(TAB + 'return { valid: true, newBoard, captured: totalCaptured }')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('function checkKo(newBoard: Board, history: string[]): boolean {')
engine_lines.append(TAB + 'const key = boardKey(newBoard)')
engine_lines.append(TAB + 'return history.length >= 2 && key === history[history.length - 2]')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function isValidMove(state: GameState, r: number, c: number): MoveResult {')
engine_lines.append(TAB + 'if (state.gameOver) return { valid: false, reason: "Game is over." }')
engine_lines.append(TAB + 'const result = tryPlaceStone(state.board, r, c, state.currentPlayer)')
engine_lines.append(TAB + 'if (!result.valid || !result.newBoard) return result')
engine_lines.append(TAB + 'if (checkKo(result.newBoard, state.history))')
engine_lines.append(TAB * 2 + 'return { valid: false, reason: "Ko rule - cannot repeat previous position." }')
engine_lines.append(TAB + 'return result')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function isValidMoveForColor(state: GameState, r: number, c: number, color: Cell): MoveResult {')
engine_lines.append(TAB + 'if (state.gameOver) return { valid: false, reason: "Game is over." }')
engine_lines.append(TAB + 'const result = tryPlaceStone(state.board, r, c, color)')
engine_lines.append(TAB + 'if (!result.valid || !result.newBoard) return result')
engine_lines.append(TAB + 'if (checkKo(result.newBoard, state.history))')
engine_lines.append(TAB * 2 + 'return { valid: false, reason: "Ko rule - cannot repeat previous position." }')
engine_lines.append(TAB + 'return result')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function placeStone(state: GameState, r: number, c: number): boolean {')
engine_lines.append(TAB + 'const result = isValidMove(state, r, c)')
engine_lines.append(TAB + 'if (!result.valid || !result.newBoard) return false')
engine_lines.append(TAB + 'state.board = result.newBoard')
engine_lines.append(TAB + 'state.history.push(boardKey(state.board))')
engine_lines.append(TAB + 'state.captures[state.currentPlayer] += result.captured!')
engine_lines.append(TAB + 'state.consecutivePasses = 0')
engine_lines.append(TAB + 'state.currentPlayer = state.currentPlayer === BLACK ? WHITE : BLACK')
engine_lines.append(TAB + 'return true')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function pass(state: GameState): void {')
engine_lines.append(TAB + 'state.consecutivePasses++')
engine_lines.append(TAB + 'state.history.push(boardKey(state.board))')
engine_lines.append(TAB + 'state.currentPlayer = state.currentPlayer === BLACK ? WHITE : BLACK')
engine_lines.append(TAB + 'if (state.consecutivePasses >= 2) state.gameOver = true')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function resign(state: GameState): void {')
engine_lines.append(TAB + 'state.gameOver = true')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function createInitialState(size: number = 19): GameState {')
engine_lines.append(TAB + 'return {')
engine_lines.append(TAB * 2 + 'size,')
engine_lines.append(TAB * 2 + 'board: createBoard(size),')
engine_lines.append(TAB * 2 + 'currentPlayer: BLACK,')
engine_lines.append(TAB * 2 + 'captures: { [BLACK]: 0, [WHITE]: 0 },')
engine_lines.append(TAB * 2 + 'history: [],')
engine_lines.append(TAB * 2 + 'consecutivePasses: 0,')
engine_lines.append(TAB * 2 + 'gameOver: false,')
engine_lines.append(TAB + '}')
engine_lines.append('}')
engine_lines.append('')
engine_lines.append('export function countScore(state: GameState): { blackScore: number; whiteScore: number } {')
engine_lines.append(TAB + 'const { board, size, captures } = state')
engine_lines.append(TAB + 'const territory: Record<number, number> = { [BLACK]: 0, [WHITE]: 0 }')
engine_lines.append(TAB + 'const visited = new Set<number>()')
engine_lines.append(TAB + 'for (let r = 0; r < size; r++) {')
engine_lines.append(TAB * 2 + 'for (let c = 0; c < size; c++) {')
engine_lines.append(TAB * 3 + 'if (board[r][c] === EMPTY && !visited.has(r * size + c)) {')
engine_lines.append(TAB * 4 + 'const borders = new Set<Cell>()')
engine_lines.append(TAB * 4 + 'const stack: [number, number][] = [[r, c]]')
engine_lines.append(TAB * 4 + 'const regionVisited = new Set<number>()')
engine_lines.append(TAB * 4 + 'while (stack.length > 0) {')
engine_lines.append(TAB * 5 + 'const [cr, cc] = stack.pop()!')
engine_lines.append(TAB * 5 + 'const key = cr * size + cc')
engine_lines.append(TAB * 5 + 'if (regionVisited.has(key)) continue')
engine_lines.append(TAB * 5 + 'regionVisited.add(key)')
engine_lines.append(TAB * 5 + 'visited.add(key)')
engine_lines.append(TAB * 5 + 'for (const [nr, nc] of getNeighbors(cr, cc, size)) {')
engine_lines.append(TAB * 6 + 'if (board[nr][nc] === EMPTY) {')
engine_lines.append(TAB * 7 + 'if (!regionVisited.has(nr * size + nc)) stack.push([nr, nc])')
engine_lines.append(TAB * 6 + '} else {')
engine_lines.append(TAB * 7 + 'borders.add(board[nr][nc])')
engine_lines.append(TAB * 6 + '}')
engine_lines.append(TAB * 5 + '}')
engine_lines.append(TAB * 4 + '}')
engine_lines.append(TAB * 4 + 'if (borders.size === 1) {')
engine_lines.append(TAB * 5 + 'const owner = [...borders][0]!')
engine_lines.append(TAB * 5 + 'territory[owner] += regionVisited.size')
engine_lines.append(TAB * 4 + '}')
engine_lines.append(TAB * 3 + '}')
engine_lines.append(TAB * 2 + '}')
engine_lines.append(TAB + '}')
engine_lines.append(TAB + 'return {')
engine_lines.append(TAB * 2 + 'blackScore: territory[BLACK] + captures[BLACK],')
engine_lines.append(TAB * 2 + 'whiteScore: territory[WHITE] + captures[WHITE] + 6.5,')
engine_lines.append(TAB + '}')
engine_lines.append('}')
w('src/engine.ts', '\n'.join(engine_lines) + '\n')

# ============================================================
# src/render.ts — CLI Renderer
# ============================================================
r = []
r.append('// Ancient Go - CLI Rendering')
r.append('import { isStarPoint, EMPTY, BLACK, WHITE, countScore } from "./engine.ts"')
r.append('import type { GameState } from "./engine.ts"')
r.append('')
r.append('export function renderBoard(state: GameState): string {')
r.append(TAB + 'const { size, board } = state')
r.append(TAB + 'const lines: string[] = []')
r.append(TAB + 'const colWidth = size > 13 ? 3 : 2')
r.append(TAB + 'let header = " ".repeat(colWidth + 1)')
r.append(TAB + 'for (let c = 0; c < size; c++) {')
r.append(TAB * 2 + 'const label = String.fromCharCode(65 + (c < 26 ? c : c - 26))')
r.append(TAB * 2 + 'header += label.padStart(colWidth)')
r.append(TAB + '}')
r.append(TAB + 'lines.push(header)')
r.append(TAB + 'lines.push("")')
r.append(TAB + 'for (let r = 0; r < size; r++) {')
r.append(TAB * 2 + 'const rowNum = (size - r).toString().padStart(colWidth)')
r.append(TAB * 2 + 'let row = rowNum + " "')
r.append(TAB * 2 + 'for (let c = 0; c < size; c++) {')
r.append(TAB * 3 + 'const cell = board[r][c]')
r.append(TAB * 3 + 'let char: string')
r.append(TAB * 3 + 'if (cell === EMPTY) {')
r.append(TAB * 4 + 'char = isStarPoint(r, c, size) ? "+" : "."')
r.append(TAB * 3 + '} else if (cell === BLACK) {')
r.append(TAB * 4 + 'char = "B"')
r.append(TAB * 3 + '} else {')
r.append(TAB * 4 + 'char = "W"')
r.append(TAB * 3 + '}')
r.append(TAB * 3 + 'row += char.padStart(colWidth)')
r.append(TAB * 2 + '}')
r.append(TAB * 2 + 'row += " " + rowNum')
r.append(TAB * 2 + 'lines.push(row)')
r.append(TAB + '}')
r.append(TAB + 'lines.push("")')
r.append(TAB + 'lines.push(header)')
r.append(TAB + 'return lines.join("\\n")')
r.append('}')
r.append('')
r.append('export function renderStatus(state: GameState): string {')
r.append(TAB + 'const turnName = state.currentPlayer === BLACK ? "Black" : "White"')
r.append(TAB + 'const turnSymbol = state.currentPlayer === BLACK ? "B" : "W"')
r.append(TAB + 'let s = "Turn: " + turnSymbol + " " + turnName')
r.append(TAB + 's += "  |  Captures - Black: " + state.captures[BLACK] + " White: " + state.captures[WHITE]')
r.append(TAB + 'if (state.consecutivePasses > 0) s += "  |  Passes: " + state.consecutivePasses + "/2"')
r.append(TAB + 'return s')
r.append('}')
r.append('')
r.append('export function parseCoord(input: string, size: number): [number, number] | null {')
r.append(TAB + 'const trimmed = input.trim().toUpperCase()')
r.append(TAB + 'const match = trimmed.match(/^([A-Z])(\\d+)$/)')
r.append(TAB + 'if (!match) return null')
r.append(TAB + 'const col = match[1]!.charCodeAt(0) - 65')
r.append(TAB + 'const rowNum = parseInt(match[2]!, 10)')
r.append(TAB + 'const row = size - rowNum')
r.append(TAB + 'if (row < 0 || row >= size || col < 0 || col >= size) return null')
r.append(TAB + 'return [row, col]')
r.append('}')
r.append('')
r.append('export function showHelp(): void {')
r.append(TAB + 'console.log("Commands:")')
r.append(TAB + 'console.log("  <col><row>   Place a stone, e.g. A1, D4, K10")')
r.append(TAB + 'console.log("  pass         Pass your turn")')
r.append(TAB + 'console.log("  resign       Resign the game")')
r.append(TAB + 'console.log("  help         Show this help")')
r.append(TAB + 'console.log("  quit         Exit")')
r.append('}')
r.append('')
r.append('export function showResult(state: GameState): void {')
r.append(TAB + 'const { blackScore, whiteScore } = countScore(state)')
r.append(TAB + 'console.log("")')
r.append(TAB + 'console.log("Final Score - Black: " + blackScore + ", White: " + whiteScore)')
r.append(TAB + 'if (blackScore > whiteScore) console.log("Black wins!")')
r.append(TAB + 'else if (whiteScore > blackScore) console.log("White wins!")')
r.append(TAB + 'else console.log("Draw!")')
r.append('}')
r.append('')
r.append('export function printUI(state: GameState): void {')
r.append(TAB + 'console.log(renderBoard(state))')
r.append(TAB + 'console.log("")')
r.append(TAB + 'console.log(renderStatus(state))')
r.append(TAB + 'console.log("")')
r.append('}')
w('src/render.ts', '\n'.join(r) + '\n')

# ============================================================
# src/bots.ts — AI Bots (direct imports from engine)
# ============================================================
b = []
b.append('/**')
b.append(' * Ancient Go - AI Bots')
b.append(' * Each bot implements selectMove(state, botColor).')
b.append(' * Pure functions — no side effects beyond Math.random().')
b.append(' */')
b.append('import { EMPTY, BLACK, WHITE } from "./engine.ts"')
b.append('import type { GameState, Cell, MoveResult } from "./engine.ts"')
b.append('')
b.append('export interface Bot {')
b.append(TAB + 'name: string')
b.append(TAB + 'selectMove(state: GameState, botColor: typeof BLACK | typeof WHITE): { r: number; c: number } | null')
b.append('}')
b.append('')
b.append('// External references (dependency injection from engine)')
b.append('let getNeighborsRef: (r: number, c: number, size: number) => [number, number][]')
b.append('let findGroupRef: (board: any[][], r: number, c: number) => [number, number][]')
b.append('let countLibertiesRef: (board: any[][], group: [number, number][]) => number')
b.append('let isValidMoveRef: (state: GameState, r: number, c: number, color: Cell) => MoveResult')
b.append('')
b.append('export function setBotDeps(')
b.append(TAB + 'getNeighbors: (r: number, c: number, size: number) => [number, number][],')
b.append(TAB + 'findGroup: (board: any[][], r: number, c: number) => [number, number][],')
b.append(TAB + 'countLiberties: (board: any[][], group: [number, number][]) => number,')
b.append(TAB + 'isValidMove: (state: GameState, r: number, c: number, color: Cell) => MoveResult')
b.append('): void {')
b.append(TAB + 'getNeighborsRef = getNeighbors')
b.append(TAB + 'findGroupRef = findGroup')
b.append(TAB + 'countLibertiesRef = countLiberties')
b.append(TAB + 'isValidMoveRef = isValidMove')
b.append('}')
b.append('')
b.append('export function createRandomBot(): Bot {')
b.append(TAB + 'return {')
b.append(TAB * 2 + 'name: "Random",')
b.append(TAB * 2 + 'selectMove(state: GameState, botColor: typeof BLACK | typeof WHITE): { r: number; c: number } | null {')
b.append(TAB * 3 + 'const { size, board } = state')
b.append(TAB * 3 + 'const empty: [number, number][] = []')
b.append(TAB * 3 + 'for (let r = 0; r < size; r++) {')
b.append(TAB * 4 + 'for (let c = 0; c < size; c++) {')
b.append(TAB * 5 + 'if (board[r][c] === EMPTY) empty.push([r, c])')
b.append(TAB * 4 + '}')
b.append(TAB * 3 + '}')
b.append(TAB * 3 + 'if (empty.length === 0) return null')
b.append(TAB * 3 + 'const start = Math.floor(Math.random() * empty.length)')
b.append(TAB * 3 + 'for (let i = 0; i < empty.length; i++) {')
b.append(TAB * 4 + 'const idx = (start + i) % empty.length')
b.append(TAB * 4 + 'const [r, c] = empty[idx]!')
b.append(TAB * 4 + 'const result = isValidMoveRef(state, r, c, botColor)')
b.append(TAB * 4 + 'if (result.valid) return { r, c }')
b.append(TAB * 3 + '}')
b.append(TAB * 3 + 'return null')
b.append(TAB * 2 + '}')
b.append(TAB + '}')
b.append('}')
b.append('')
b.append('export function createGreedyBot(): Bot {')
b.append(TAB + 'return {')
b.append(TAB * 2 + 'name: "Greedy",')
b.append(TAB * 2 + 'selectMove(state: GameState, botColor: typeof BLACK | typeof WHITE): { r: number; c: number } | null {')
b.append(TAB * 3 + 'const { size, board } = state')
b.append(TAB * 3 + 'const opponent: Cell = botColor === BLACK ? WHITE : BLACK')
b.append(TAB * 3 + '// Priority 1: Capture enemy groups with 1 liberty')
b.append(TAB * 3 + 'for (let r = 0; r < size; r++) {')
b.append(TAB * 4 + 'for (let c = 0; c < size; c++) {')
b.append(TAB * 5 + 'if (board[r][c] === opponent) {')
b.append(TAB * 6 + 'const group = findGroupRef(board, r, c)')
b.append(TAB * 6 + 'if (countLibertiesRef(board, group) === 1) {')
b.append(TAB * 7 + 'for (const [gr, gc] of group) {')
b.append(TAB * 8 + 'for (const [nr, nc] of getNeighborsRef(gr, gc, size)) {')
b.append(TAB * 9 + 'if (board[nr][nc] === EMPTY) {')
b.append(TAB * 10 + 'const result = isValidMoveRef(state, nr, nc, botColor)')
b.append(TAB * 10 + 'if (result.valid) return { r: nr, c: nc }')
b.append(TAB * 9 + '}')
b.append(TAB * 8 + '}')
b.append(TAB * 7 + '}')
b.append(TAB * 6 + '}')
b.append(TAB * 5 + '}')
b.append(TAB * 4 + '}')
b.append(TAB * 3 + '}')
b.append(TAB * 3 + '// Priority 2: Defend own groups with 1 liberty')
b.append(TAB * 3 + 'for (let r = 0; r < size; r++) {')
b.append(TAB * 4 + 'for (let c = 0; c < size; c++) {')
b.append(TAB * 5 + 'if (board[r][c] === botColor) {')
b.append(TAB * 6 + 'const group = findGroupRef(board, r, c)')
b.append(TAB * 6 + 'if (countLibertiesRef(board, group) === 1) {')
b.append(TAB * 7 + 'for (const [gr, gc] of group) {')
b.append(TAB * 8 + 'for (const [nr, nc] of getNeighborsRef(gr, gc, size)) {')
b.append(TAB * 9 + 'if (board[nr][nc] === EMPTY) {')
b.append(TAB * 10 + 'const result = isValidMoveRef(state, nr, nc, botColor)')
b.append(TAB * 10 + 'if (result.valid) return { r: nr, c: nc }')
b.append(TAB * 9 + '}')
b.append(TAB * 8 + '}')
b.append(TAB * 7 + '}')
b.append(TAB * 6 + '}')
b.append(TAB * 5 + '}')
b.append(TAB * 4 + '}')
b.append(TAB * 3 + '}')
b.append(TAB * 3 + '// Priority 3: Center-biased random')
b.append(TAB * 3 + 'const center = (size - 1) / 2')
b.append(TAB * 3 + 'const candidates: Array<{ r: number; c: number; score: number }> = []')
b.append(TAB * 3 + 'for (let r = 0; r < size; r++) {')
b.append(TAB * 4 + 'for (let c = 0; c < size; c++) {')
b.append(TAB * 5 + 'if (board[r][c] === EMPTY) {')
b.append(TAB * 6 + 'const result = isValidMoveRef(state, r, c, botColor)')
b.append(TAB * 6 + 'if (result.valid) {')
b.append(TAB * 7 + 'const dist = Math.abs(r - center) + Math.abs(c - center)')
b.append(TAB * 7 + 'candidates.push({ r, c, score: dist + Math.random() * 3 })')
b.append(TAB * 6 + '}')
b.append(TAB * 5 + '}')
b.append(TAB * 4 + '}')
b.append(TAB * 3 + '}')
b.append(TAB * 3 + 'if (candidates.length === 0) return null')
b.append(TAB * 3 + 'candidates.sort((a, b) => a.score - b.score)')
b.append(TAB * 3 + 'return { r: candidates[0]!.r, c: candidates[0]!.c }')
b.append(TAB * 2 + '}')
b.append(TAB + '}')
b.append('}')
w('src/bots.ts', '\n'.join(b) + '\n')

# ============================================================
# src/script.ts — Entry point (thin)
# ============================================================
s = []
s.append('// Ancient Go - Entry Point')
s.append('import * as readline from "readline"')
s.append('import type { GameState, Cell } from "./engine.ts"')
s.append('import { BLACK, WHITE, createInitialState, pass, placeStone, resign, countScore } from "./engine.ts"')
s.append('import { renderBoard, renderStatus, printUI, showHelp, showResult, parseCoord } from "./render.ts"')
s.append('import { createRandomBot, createGreedyBot, setBotDeps } from "./bots.ts"')
s.append('import type { Bot } from "./bots.ts"')
s.append('import { getNeighbors, findGroup, countLiberties, isValidMoveForColor } from "./engine.ts"')
s.append('')
s.append('// Wire up bot dependencies')
s.append('setBotDeps(getNeighbors, findGroup, countLiberties, isValidMoveForColor)')
s.append('')
s.append('async function main(): Promise<void> {')
s.append(TAB + 'console.log("=== ANCIENT GO ===\\n")')
s.append(TAB + '')
s.append(TAB + 'const rl = readline.createInterface({')
s.append(TAB * 2 + 'input: process.stdin,')
s.append(TAB * 2 + 'output: process.stdout,')
s.append(TAB + '})')
s.append(TAB + '')
s.append(TAB + 'let state: GameState | null = null')
s.append(TAB + 'let awaitingSize = true')
s.append(TAB + 'let bot: Bot | null = null')
s.append(TAB + 'let humanColor: typeof BLACK | typeof WHITE = BLACK')
s.append(TAB + 'let botColor: typeof BLACK | typeof WHITE = WHITE')
s.append(TAB + 'let awaitingAiSetup = false')
s.append(TAB + 'let waitingForAiColor = false')
s.append(TAB + 'let waitingForAiDifficulty = false')
s.append(TAB + '')
s.append(TAB + 'rl.question("Board size? (9/13/19) [19]: ", (answer) => {')
s.append(TAB * 2 + 'const n = parseInt(answer.trim(), 10)')
s.append(TAB * 2 + 'const size = [9, 13, 19].includes(n) ? n : 19')
s.append(TAB * 2 + 'state = createInitialState(size)')
s.append(TAB * 2 + 'awaitingSize = false')
s.append(TAB * 2 + 'awaitingAiSetup = true')
s.append(TAB * 2 + 'rl.question("Play against AI? (y/n) [n]: ", (aiAnswer) => {')
s.append(TAB * 3 + 'const wantsAi = aiAnswer.trim().toLowerCase() === "y"')
s.append(TAB * 3 + 'if (!wantsAi) {')
s.append(TAB * 4 + 'showHelp()')
s.append(TAB * 4 + 'printUI(state)')
s.append(TAB * 4 + 'return')
s.append(TAB * 3 + '}')
s.append(TAB * 3 + 'awaitingAiDifficulty = true')
s.append(TAB * 3 + 'rl.question("Choose difficulty (1=Random, 2=Greedy) [2]: ", (diffAnswer) => {')
s.append(TAB * 4 + 'bot = diffAnswer.trim() === "1" ? createRandomBot() : createGreedyBot()')
s.append(TAB * 4 + 'awaitingAiDifficulty = false')
s.append(TAB * 4 + 'waitingForAiColor = true')
s.append(TAB * 4 + 'rl.question("Your color? (B/black or W/white) [B]: ", (colorAnswer) => {')
s.append(TAB * 5 + 'const c = colorAnswer.trim().toLowerCase()')
s.append(TAB * 5 + 'humanColor = (c === "w" || c === "white") ? WHITE : BLACK')
s.append(TAB * 5 + 'botColor = humanColor === BLACK ? WHITE : BLACK')
s.append(TAB * 5 + 'waitingForAiColor = false')
s.append(TAB * 5 + 'awaitingAiSetup = false')
s.append(TAB * 5 + 'showHelp()')
s.append(TAB * 5 + 'printUI(state)')
s.append(TAB * 5 + 'if (state && bot && state.currentPlayer === botColor) {')
s.append(TAB * 6 + 'triggerBotMove(state, bot, botColor, rl)')
s.append(TAB * 5 + '}')
s.append(TAB * 4 + '})')
s.append(TAB * 3 + '})')
s.append(TAB * 2 + '})')
s.append(TAB + '})')
s.append(TAB + '')
s.append(TAB + 'function triggerBotMove(s: GameState, b: Bot, bColor: typeof BLACK | typeof WHITE, rli: readline.Interface): void {')
s.append(TAB * 2 + 'console.log("  [AI] Thinking...")')
s.append(TAB * 2 + 'const move = b.selectMove(s, bColor)')
s.append(TAB * 2 + 'if (move === null) {')
s.append(TAB * 3 + 'console.log("  [AI] passes.")')
s.append(TAB * 3 + 'pass(s)')
s.append(TAB * 3 + 'if (s.gameOver) { printUI(s); showResult(s); rli.close(); process.exit(0) }')
s.append(TAB * 3 + 'printUI(s)')
s.append(TAB * 3 + 'if (!s.gameOver && s.currentPlayer === bColor) setTimeout(() => triggerBotMove(s, b, bColor, rli), 100)')
s.append(TAB * 3 + 'return')
s.append(TAB * 2 + '}')
s.append(TAB * 2 + 'const ok = placeStone(s, move.r, move.c)')
s.append(TAB * 2 + 'if (ok) {')
s.append(TAB * 3 + 'const rowLabel = s.size - move.r')
s.append(TAB * 3 + 'console.log("  [AI] plays " + String.fromCharCode(65 + move.c) + rowLabel + ".")')
s.append(TAB * 2 + '}')
s.append(TAB * 2 + 'printUI(s)')
s.append(TAB * 2 + 'if (s.gameOver) { showResult(s); rli.close(); process.exit(0) }')
s.append(TAB + '}')
s.append(TAB + '')
s.append(TAB + 'rl.on("line", (line: string) => {')
s.append(TAB * 2 + 'if (awaitingSize || awaitingAiSetup || awaitingAiDifficulty || waitingForAiColor) return')
s.append(TAB * 2 + 'if (!state) return')
s.append(TAB * 2 + 'const cmd = line.trim().toLowerCase()')
s.append(TAB * 2 + 'if (cmd === "quit" || cmd === "exit") { console.log("Goodbye!"); rl.close(); process.exit(0) }')
s.append(TAB * 2 + 'if (cmd === "help") { showHelp(); printUI(state); return }')
s.append(TAB * 2 + 'if (cmd === "pass") {')
s.append(TAB * 3 + 'pass(state)')
s.append(TAB * 3 + 'if (state.gameOver) { printUI(state); showResult(state); rl.close(); process.exit(0) }')
s.append(TAB * 3 + 'printUI(state)')
s.append(TAB * 3 + 'if (bot && state.currentPlayer === botColor) setTimeout(() => triggerBotMove(state, bot, botColor, rl), 100)')
s.append(TAB * 3 + 'return')
s.append(TAB * 2 + '}')
s.append(TAB * 2 + 'if (cmd === "resign") {')
s.append(TAB * 3 + 'if (bot) { console.log("  [RESIGN] Human resigns. AI wins!") }')
s.append(TAB * 3 + 'else { resign(state) }')
s.append(TAB * 3 + 'showResult(state); rl.close(); process.exit(0)')
s.append(TAB * 2 + '}')
s.append(TAB * 2 + 'if (bot && state.currentPlayer !== humanColor) {')
s.append(TAB * 3 + 'console.log("  [X] It\'s the AI\'s turn. Wait...")')
s.append(TAB * 3 + 'printUI(state); return')
s.append(TAB * 2 + '}')
s.append(TAB * 2 + 'const coord = parseCoord(line, state.size)')
s.append(TAB * 2 + 'if (!coord) { console.log("  [X] Invalid: \\"" + line + "\\". Type help for commands."); printUI(state); return }')
s.append(TAB * 2 + 'placeStone(state, coord[0], coord[1])')
s.append(TAB * 2 + 'if (state.gameOver) { printUI(state); showResult(state); rl.close(); process.exit(0) }')
s.append(TAB * 2 + 'printUI(state)')
s.append(TAB * 2 + 'if (bot && state.currentPlayer === botColor) setTimeout(() => triggerBotMove(state, bot, botColor, rl), 100)')
s.append(TAB + '})')
s.append(TAB + '')
s.append('}')
s.append('')
s.append('main().catch(console.error)')
s.append('')
w('src/script.ts', '\n'.join(s) + '\n')

# Clean up old root-level files that have been replaced
for old in ['script.ts', 'bots.ts']:
    if os.path.exists(old):
        os.remove(old)
        print(f'Removed {old} (replaced by src/{old})')

print('All source files written!')

